title: Dustin Ingram
author:
  name: Dustin Ingram
production_url: https://dustingram.com

# Build settings
permalink: /:categories/:year/:month/:day/:title
markdown: kramdown
exclude:
  - README.md

# Analytics
analytics :
  google :
      tracking_id : 'UA-2445654-1'
